### PR TITLE
Administration screen

### PR DESCRIPTION
**Pull request by carloso0114**
# Description

What did you implemented/Why did you implemented this:

- Create admin table, using bcrypt gem to hide password in the database, create a form so we can try if the username matches the password. If password is correct, you would be redirected to a portal page under construcion else, to the same form, because we need to authenticate ourselves in order to access to the portal.
- (Authentication is not being saved at the moment (session) this will be implemented in the future)

## Testing

As always, run:
rails db:drop
rails db:create
rails db:migrate
rails db:seed

Go to the admin login (administrador) (top right corner of the screen ) and use the following credentials:
username: pepe 
password: a123

### CODE REVIEW

**Review by dagp-ucol — APPROVED** [review]
Remember to resolve conflicts in the branch before merging.
LGTM 🙂.

**Comment by dagp-ucol** [comment]
Wednesday we will have a Git Workshop, that may help to fix that type of problems 🙂✌️

**Review by MarcoRodriguez23 — COMMENTED** [review]
your database.yml file should not be visible, add it to the .gitignore file

**Review by oscaregr — APPROVED** [review]
LGTM

**Review by Reiyirak — APPROVED** [review]
LGTM

**Pull request merged**
